apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpc-server
  namespace: grpc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grpc-server
      name: grpc-server
  template:
    metadata:
      labels:
        app: grpc-server
        name: grpc-server
    spec:
      containers:
        - name: grpc-server
          image: wxlsh/grpc-server:latest
          ports:
            - containerPort: 50051
          env:
            - name: GRPC_PORT
              value: "50051"
---
apiVersion: v1
kind: Service
metadata:
  name: grpc-server
  namespace: grpc
spec:
  selector:
    app: grpc-server
  ports:
    - protocol: TCP
      port: 50051
      targetPort: 50051
